%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/kai/Desktop/Vibro/Vibrotactile_Experiment1/Analysis_Final/Data/demographics.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 25-Oct-2023 11:03:15

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:D42";

% Specify column names and types
opts.VariableNames = ["Age", "Gender", "MSI_Percept", "MSI_Train"];
opts.VariableTypes = ["double", "categorical", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Gender", "EmptyFieldRule", "auto");

% Import the data
demographics = readtable("demographics.xlsx", opts, "UseExcel", false);



%% Clear temporary variables
clear opts