%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/kaisiedenburg/ownCloud/Home-Cloud/MusicProjects/Projects/Vibrotactile/Analysis_Script_Matlab/Data/EMO.xls
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 04-Jul-2023 21:31:35

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:I705";

% Specify column names and types
opts.VariableNames = ["SongIdx", "CondIdx", "Pleasantness", "Arousal", "Groove", "LivePerformance", "BeingPart", "Liking", "SubjID"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
%cohort1 = readtable("/Users/kai/UOL_MPPL/Projects/VibroChair/Vibrotactile_Experiment1/Analysis_Final/AllFiles/EMO_exp1.xls", opts, "UseExcel", false);
cohort1 = readtable("EMO_exp1.xls", opts, "UseExcel", false);

%% Clear temporary variables
clear opts