%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/kaisiedenburg/ownCloud/Home-Cloud/MusicProjects/Projects/Vibrotactile/Analysis_Script_Matlab/Data/EMO_1.xls
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 05-Jul-2023 10:18:26

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:I609";

% Specify column names and types
opts.VariableNames = ["SongIdx", "CondIdx", "Pleasantness", "Arousal", "Groove", "LivePerformance", "BeingPart", "Liking", "SubjID"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
cohort2 = readtable("EMO_exp2.xls", opts, "UseExcel", false);


%% Clear temporary variables
clear opts